{% set name = "gpyconform" %}
{% set version = "0.1.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gpyconform-{{ version }}.tar.gz
  sha256: 1d585f639a294c3123353f171801d0bdc328c115ad6fd6f66e95ea5ef4f51ceb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.0
    - gpytorch ==1.13
    - linear_operator >=0.5.3
    - numpy

test:
  imports:
    - gpyconform
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: "https://github.com/harrisp/GPyConform"
  summary: "Extends GPyTorch with Gaussian Process Regression Conformal Prediction"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "LICENSE.txt"
  doc_url: "https://gpyconform.readthedocs.io/"
  dev_url: "https://github.com/harrisp/GPyConform"

extra:
  recipe-maintainers:
    - harrisp
